SELECT member_id,
       member_name,
       CASE
           WHEN gender = '1' THEN 'Female'
           WHEN gender = '0' THEN 'Male'
           ELSE gender
           END        as gender,
       age,
       country_id,
       country,
       project_id,
       fiscal_year_id,
       fiscal_year_name,
       catchment_id,
       village,
       office_id,
       branch,
       house_hold_id,
       house_hold_serial_number,
       participant_id as member_serial,
       member_type,
       group_id,
       group_name,
       group_type_id,
       group_type_name,
       service_point_id,
       service_point_name,
       mf_status,
       ep_member_mf_status,
       ep_hh_mf_status,
       received_livelihood,
       aim_ep_h1a_receivedlivelihood,
       aim_ep_i3_hh_catagory,
       economic_status,
       economic_status_from_entry,
       hh_profile_status,
       school_satus,
       want_to_back_to_school,
       has_support_to_manage_livelihood,
       participant_type,
       total_session,
       present_session,
       percentage,
       eligible_process,
       id,
       last_modified_time,
       received_livelihood_text,
       mf_status_info,
       profile_status,
       economic_status_from_entry_label,
       want_to_back_school,
       has_support_manage_livelihood,
       is_pwd
FROM customdataset.c2_livelihood_eligible_participants -- taken c2 data into it . it is static table.
UNION
SELECT member_id,
       member_name,
       CASE
           WHEN gender = '1' THEN 'Female'
           WHEN gender = '0' THEN 'Male'
           ELSE gender
           END      as gender,
       age,
       country_id,
       country,
       project_id,
       fiscal_year_id,
       fiscal_year_name,
       catchment_id,
       village,
       office_id,
       branch,
       house_hold_id,
       house_hold_serial_number,
       member_serial,
       member_type,
       group_id,
       group_name,
       group_type_id,
       group_type_name,
       service_point_id,
       service_point_name,
       mf_status,
       ep_member_mf_status,
       ep_hh_mf_status,
       received_livelihood,
       aim_ep_h1a_receivedlivelihood,
       aim_ep_i3_hh_catagory,
       economic_status,
       economic_status_from_entry,
       hh_profile_status,
       school_satus,
       want_to_back_to_school,
       has_support_to_manage_livelihood,
       participant_type,
       total_session,
       present_session,
       percentage,
       'calculated' as eligible_process,
       id,
       last_modified_time,
       received_livelihood_text,
       mf_status_info,
       profile_status,
       economic_status_from_entry_label,
       want_to_back_school,
       has_support_manage_livelihood,
       is_pwd
FROM customdataset.c3_livelihood_eligible_participants;